### PR TITLE
fix email settings pop-up references wrong course

### LINKED ISSUE #379: Email settings pop-up references wrong course
We recently merged #375 to display a pop-up for unsubscribing from course emails. It seems like there's a mismatch between the course the user clicks on, and the course in the pop-up. It appears that the API call matches the course in the pop-up. 

### Steps to Reproduce

1.  Enroll in at least two courses on rc.mitxonline.mit.edu 
2. Go to the dashboard and click email settings for one of the courses. 
3. Change the setting and click save. Note the api request. 

### Expected Behavior

- The course number in the pop-up should correspond to the course that was clicked on. 
- The api request should go to the same course enrollment id. 

### Actual Behavior

- The pop-up displays a different course number
- When saving the setting, the API call goes to the wrong enrollment id

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #379 

#### What's this PR do?
fix email settings pop-up references wrong course

#### How should this be manually tested?
Please see the ticket description

#### Screenshots (if appropriate)
Screenshot 2022-01-24 at 19 20 57
Screenshot 2022-01-24 at 19 21 21
Screenshot 2022-01-24 at 19 21 35
Screenshot 2022-01-24 at 19 21 48

### CODE REVIEW

File: static/js/containers/pages/DashboardPage.js [hunk 1]
```diff
@@ -194,53 +184,60 @@ export class DashboardPage extends React.Component<
...
-                </Button>{" "}
-                <Button onClick={this.toggleEmailSettingsModalVisibility}>
-                  Cancel
-                </Button>
-              </Form>
-            )}
-          />
-        </ModalBody>
-      </Modal>
+        <div className="modal-dialog">
```
Comment (arslanashraf7) [inline static/js/containers/pages/DashboardPage.js:192]: This is however showing the correct course number on the title but it has introduced some issues alongside.

1) The issue is that the model is not maintaining the state properly now.

**Reproduction steps:**
Click on `Email Settings` in the menu for any enrolled course, Uncheck the `Receive Course emails` box and click the close button instead of clicking save. Now when reopened this should still be because the user didn't save the settings but instead it staus unchecked.

2) I don't understand why we removed the <Modal> completely and went to our own html design?

**Review by arslanashraf7 — CHANGES_REQUESTED** [review]
I left a few comments.

File: static/scss/layout.scss [hunk 2]
```diff
@@ -36,7 +36,6 @@ body {
   .main-panel {
     flex: 1;
     min-height: calc(100vh - 351px);
-    z-index: 1;
```
[the remark this answers is not in the document]
Comment (umarmughal824) [reply static/scss/layout.scss:39]: fixed now

**Comment by umarmughal824** [comment]
@arslanashraf7 remember it's pre-requisite is https://github.com/mitodl/mitxonline/pull/385 as we had reverted it so that's why we are getting merge conflicts. So on merged #385 these merge conflicts will remain no more.

**Comment by arslanashraf7** [comment]
> @arslanashraf7 remember it's pre-requisite is #385 as we had reverted it in #381 so that's why we are getting merge conflicts. So on merging #385 these merge conflicts will be resolved.

@umarmughal824 I understand but it won't be testable directly in this state. Additionally, I think you can base this PR on https://github.com/mitodl/mitxonline/pull/385 or cherry-pick the changes from there to make it a whole PR with the overall functionality and I can review all of it together.
After that you might close https://github.com/mitodl/mitxonline/pull/385

**Comment by umarmughal824** [comment]
> > @arslanashraf7 remember it's pre-requisite is #385 as we had reverted it in #381 so that's why we are getting merge conflicts. So on merging #385 these merge conflicts will be resolved.
> 
> @umarmughal824 I understand but it won't be testable directly in this state. Additionally, I think you can base this PR on #385 or cherry-pick the changes from there to make it a whole PR with the overall functionality and I can review all of it together. After that you might close #385

#385 doesn't need any review. Just review it as it will be the final PR as it's based on master before revert. So once you will approve it. We will merge both together.

**Comment by arslanashraf7** [comment]
> > > @arslanashraf7 remember it's pre-requisite is #385 as we had reverted it in #381 so that's why we are getting merge conflicts. So on merging #385 these merge conflicts will be resolved.
> > 
> > 
> > @umarmughal824 I understand but it won't be testable directly in this state. Additionally, I think you can base this PR on #385 or cherry-pick the changes from there to make it a whole PR with the overall functionality and I can review all of it together. After that you might close #385
> 
> #385 doesn't need any review. Just review it as it will be the final PR as it's based on master before revert #381. So once you will approve it, we will merge both together. **As both have separate tickets, I would like to keep them separate.**

@umarmughal824 I don't think I understand. in order to review and test this PR it would be nice to have it in working condition which is not the case for this PR right now.

How do you propose I test the changes in this PR?

File: static/js/containers/pages/DashboardPage.js [hunk 3]
```diff
@@ -77,13 +77,20 @@ export class DashboardPage extends React.Component<
...
 
-  toggleEmailSettingsModalVisibility = () => {
+  toggleEmailSettingsModalVisibility = (enrollmentId: number) => {
     const { emailSettingsModalVisibility } = this.state
+    let isOpen = false
+    if (emailSettingsModalVisibility[enrollmentId] === undefined) {
+      isOpen = true
+    } else {
+      isOpen = !emailSettingsModalVisibility[enrollmentId]
+    }
```
Comment (arslanashraf7) [inline static/js/containers/pages/DashboardPage.js:90]: I see this same logic for checking which items being opened have been used on multiple places can you convert that into a method and call it here and on the other place?

File: static/js/containers/pages/DashboardPage.js [hunk 4]
```diff
@@ -193,13 +200,22 @@ export class DashboardPage extends React.Component<
 
   renderEmailSettingsDialog(enrollment: RunEnrollment) {
     const { emailSettingsModalVisibility } = this.state
+    let isOpen = false
+    if (emailSettingsModalVisibility[enrollment.id] === undefined) {
+      isOpen = false
+    } else {
+      isOpen = emailSettingsModalVisibility[enrollment.id]
+    }
```
Comment (arslanashraf7) [inline static/js/containers/pages/DashboardPage.js:208]: This is the other place as mentioned in my above comment.

**Review by arslanashraf7 — CHANGES_REQUESTED** [review]
Some minor changes related to reusability.

**Comment by umarmughal824** [comment]
> > > > @arslanashraf7 remember it's pre-requisite is #385 as we had reverted it in #381 so that's why we are getting merge conflicts. So on merging #385 these merge conflicts will be resolved.
> > > 
> > > 
> > > @umarmughal824 I understand but it won't be testable directly in this state. Additionally, I think you can base this PR on #385 or cherry-pick the changes from there to make it a whole PR with the overall functionality and I can review all of it together. After that you might close #385
> > 
> > 
> > #385 doesn't need any review. Just review it as it will be the final PR as it's based on master before revert #381. So once you will approve it, we will merge both together. **As both have separate tickets, I would like to keep them separate.**
> 
> @umarmughal824 I don't think I understand. in order to review and test this PR it would be nice to have it in working condition which is not the case for this PR right now.
> 
> How do you propose I test the changes in this PR?

this is in working condition. You need to simply check out that branch after fetching.

File: static/js/containers/pages/DashboardPage.js (hunk 3 above)
Comment (umarmughal824) [reply static/js/containers/pages/DashboardPage.js:90]: It's not the same because Line#89 is updating the value

File: static/js/containers/pages/DashboardPage.js (hunk 4 above)
Comment (umarmughal824) [reply static/js/containers/pages/DashboardPage.js:208]: here we are not updating anything just fetching it out

File: static/js/containers/pages/DashboardPage.js (hunk 3 above)
Comment (umarmughal824) [reply static/js/containers/pages/DashboardPage.js:90]: Line#87 setting `isOpen=true` but in the next occurrence it's consider as false

**Review by arslanashraf7 — APPROVED** [review]
👍
